### ISSUE TITLE
TODO before stable release

### ISSUE THREAD

**Issue by willnode** [willnode/webpack-explorer#1]
- [ ] Small sidebar applet quickly explaining how webpack config works
- [ ] Callouts (replace tooltip for callouts) on everywhere
- [ ] Have a clear explanation how to setup `dev` vs `prod`.
- [x] Path consistency for `entry` (must relative) and `output` (must absolute).
- [ ] Have resolve alias, and other configurations that common in usage.

To be discussed:
- [ ] Let users download script for automation (one-click run to setup webpack and depedencies automagically)

Other things to note:
- [ ] No false/mistypo in config output
- [x] Write tests
